'use client';
import type { ReactNode } from 'react';
import { ArrowUpRight, ChevronRight } from 'lucide-react';
import type { ExecutiveSnapshot } from '@/lib/executive-model';
import { ownerHref, type OwnerRoute } from '@/lib/owner-model';
import { al1Sections, type Al1Section } from '@/lib/al1-ceo-model';
import { airResourceSummary, airSafetySummary, airValue, airMonths, airSum, type AirlineId } from '@/lib/airline-model';
import { sqSummary } from '@/lib/al1-safety-model';
import { Trend } from './al1-ceo-workspace';
import CompanyNavigation from './company-navigation';
import { MetricHelp } from './metric-help';

const n = (v: number | null | undefined, d = 1) => v == null ? '—' : new Intl.NumberFormat('ru-RU', { maximumFractionDigits: d }).format(v).replace('-', '−');
const month = (m: string) => ['Янв','Фев','Мар','Апр','Май','Июн','Июл','Авг','Сен','Окт','Ноя','Дек'][Number(m.slice(5,7))-1];
const date = (d: string) => d.slice(8,10)+'.'+d.slice(5,7);

export default function CompanyOverview({ data, route }: { data: ExecutiveSnapshot; route: OwnerRoute }) {
  const a = data.airlines?.[route.company as AirlineId];
  if (!a || a.snapshotId !== data.snapshotId || a.asOf !== data.asOf) return <section className="op-panel">Срез компании недоступен.</section>;
  const scope = { start: route.start || '2026-01', end: route.end || '2026-12' };
  if (!airMonths.includes(scope.start) || !airMonths.includes(scope.end) || scope.start > scope.end) return <section className="op-panel">Некорректный период. <a href={ownerHref({page:'company',company:a.companyId,snapshot:a.snapshotId})}>Сбросить период</a></section>;
  const e = a.entity, r = airResourceSummary(a,scope), sq = airSafetySummary(a,scope);
  const al1Sq = a.companyId === 'AL1' && data.safety ? sqSummary(data.safety,scope) : null;
  const go = (metric?: string, kpi?: string, id?: string, field: OwnerRoute['field'] = 'forecast') => ownerHref({page:'company',company:a.companyId,snapshot:a.snapshotId,...scope,metric,kpi,id,field});
  const value = (key: string, view: 'plan'|'actual'|'forecast' = 'forecast') => airValue(a,scope,key,view);
  const trend = (key: string) => airMonths.filter(m => m >= scope.start && m <= scope.end).map(m => ({label:month(m),plan:airValue(a,{start:m,end:m},key,'plan'),actual:airValue(a,{start:m,end:m},key,'actual'),forecast:m > '2026-08' ? airValue(a,{start:m,end:m},key,'forecast') : null}));
  const flow = (key: 'op'|'revenue') => e.monthly[key].filter(m=>m.month>=scope.start&&m.month<=scope.end).map(m=>({label:month(m.month),plan:m.plan,actual:m.actual,forecast:m.actual===null?m.forecast:null}));
  const repairs = a.repairs.filter(x=>!x.actualReturn && x.eta>=a.asOf).sort((x,y)=>x.eta.localeCompare(y.eta));
  const urgent = repairs.find(x=>x.eta>x.planReturn) || repairs[0];
  const blockedCrew = r.crew.find(x=>x.status==='BLOCKED') || r.crew.find(x=>x.status!=='CONFIRMED');
  const minimum = Math.min(e.cash,...e.weeks.map(w=>w.balance));
  const margin = value('revenue') ? 100*value('op')!/value('revenue')! : null;
  const profile = a.companyId === 'AL1' ? 'Чартерные перевозки' : a.companyId === 'AL2' ? 'Регулярные и чартерные перевозки' : 'Регулярная программа и отдельные чартеры';
  const item = (label: string, val: string, section: string, key: string, sub?: string, catalog: 'airline'|'executive'|'safety'='airline', field: OwnerRoute['field']='forecast') => <div className="al1-metric"><span>{label} <MetricHelp catalog={key==='banks'?'finance':key==='liquidity'||key==='calendar'?'airline':catalog} metric={key==='banks'?'balance':key==='calendar'?'liquidity':key}/></span><a href={go(section,key,undefined,field)}><strong>{val}</strong>{sub&&<small>{sub}</small>}</a></div>;
  const card = (s: Al1Section, children: ReactNode) => <section className={'op-panel al1-card al1-'+s} key={s} data-company-block={s}><header><a href={go(s)}><h2>{al1Sections[s][0]}</h2><span>{al1Sections[s][1]}</span></a><a className="al1-open" aria-label={'Раскрыть: '+al1Sections[s][0]} href={go(s)}><ArrowUpRight size={20}/></a></header>{children}<a className="al1-card-footer" href={go(s)}>{al1Sections[s][2]}<ChevronRight size={16}/></a></section>;
  const parts: Record<Al1Section, ReactNode> = {
    economics: <><div className="al1-metrics">{item('Выручка · прогноз',n(value('revenue'))+' млн ₽','economics','revenue','План '+n(value('revenue','plan')),'executive')}{item('Операционная прибыль · M4',n(value('op'))+' млн ₽','economics','op','План '+n(value('op','plan')),'executive')}{item('Операционная маржа',n(margin)+'%','economics','margin',undefined,'executive')}</div><Trend rows={flow('op')} unit="млн ₽"/><a className="al1-note" href={go('economics',a.companyId==='AL1'?'costs':'opex')}>Операционные расходы {n(value('revenue')!-value('op')!)} млн ₽ · статьи и отклонения →</a></>,
    commerce: <><div className="al1-metrics">{item('Будущая выручка',n(e.portfolio.total)+' млн ₽','commerce','portfolio','Сентябрь–декабрь','executive')}{item('Подтверждено',n(e.portfolio.confirmed)+' млн ₽','commerce','portfolio',n(e.portfolio.total?100*e.portfolio.confirmed/e.portfolio.total:null)+'% будущей выручки','executive')}</div><Trend rows={flow('revenue')} unit="млн ₽"/><p>{a.companyId==='AL1'?'Заказ → миссия → полная ротация, включая перегоны и ожидание.':a.companyId==='AL2'?'Общий результат и два раздельных контура: регулярная программа и чартеры.':'Направление → программа → вылет. Загрузка и доходность рассматриваются вместе.'}</p><a className="al1-note" href={go('commerce')}>Доходность, стоимость перевозки и продажи →</a></>,
    production: <><div className="al1-metrics">{item('Общий налёт · прогноз',n(value('hours'))+' ч','production','hours','План '+n(value('hours','plan'))+' ч')}{item('Факт налёта',n(value('hours','actual'))+' ч','production','hours','Закрытая часть периода','airline','actual')}</div><Trend rows={trend('hours')} unit="ч"/><a className="al1-note" href={go('production')}>Программа, выполненные рейсы, мощность, груз и топливо →</a></>,
    technical: <><div className="al1-metrics">{item('Исправные ВС',r.ready+' / '+r.planes.length,'technical','ready','На 31 августа')}{item('Доступность парка',n(r.availability)+'%','technical','availability','Календарное время закрытой части')}</div><div className="al1-plane-strip" aria-label="Состояние парка">{r.planes.map(p=><a href={go('technical',undefined,p.id)} key={p.id} className={p.status==='READY'?'ready':'unready'} title={p.id+' · '+p.status}>{a.fleets.find(f=>f.id===p.fleet)?.aircraft}<small>{p.id.replace('DEMO-','')}</small></a>)}</div><div className="al1-mini-list">{repairs.slice(0,2).map(x=><a key={x.id} href={go('technical',undefined,x.id)}><span>{x.title}</span><b>{date(x.eta)}<small>ожидаемый возврат</small></b></a>)}</div></>,
    finance: <><div className="al1-metrics">{item('Деньги на счетах',n(e.cash)+' млн ₽','finance',a.companyId==='AL1'?'banks':'cash','На 31 августа','executive')}{item('Минимум на 13 недель',n(minimum)+' млн ₽','finance',a.companyId==='AL1'?'calendar':'liquidity',minimum<0?'Потребность в финансировании':'Прогноз остатка','executive')}</div><Trend rows={e.weeks.map(w=>({label:date(w.date),forecast:w.balance,reserve:e.cashFloor}))} unit="млн ₽" cash/><a className="al1-note" href={go('finance')}>OCF {n(e.flows.ocf.forecast)} · CAPEX {n(e.flows.capex.forecast)} · FCF {n(e.flows.fcf.forecast)} млн ₽ за год →</a></>,
    people: <><div className="al1-metrics">{item('Численность / план',r.hc+' / '+airSum(a.departments.map(d=>d.plan)),'people','hc','На 31 августа · FTE '+n(r.fte))}{item('Проверки назначений',r.confirmed+' / '+r.crew.length,'people','crew','Будущие рейсы · допуск к вылету отдельно')}</div><div className="al1-bars">{a.fleets.map(f=>{const rows=r.crew.filter(c=>c.fleet===f.id),pass=rows.filter(c=>c.status==='CONFIRMED').length;return <a key={f.id} href={go('people','crew')+'&fleet='+f.id}><span>{f.aircraft}</span><i><b style={{width:(rows.length?100*pass/rows.length:0)+'%'}}/></i><strong>{pass} / {rows.length}</strong></a>;})}</div><a className="al1-note" href={go('people','crew')}>Препятствия {r.blocked} · нет подтверждения {r.unknown} · устарело {r.stale} →</a></>,
    safety: <><div className="al1-metrics">{item(a.companyId==='AL1'?'Неприемлемые риски':'Открытые риски безопасности',n(al1Sq?.unacceptable??a.records.filter(x=>x.kind==='risk').length,0),'safety','risks','На 31 августа',a.companyId==='AL1'?'safety':'airline')}{item('Исполнение программы',n(al1Sq?al1Sq.service:sq.service)+'%','safety','service','Нарушений '+(al1Sq?.missed??sq.failures.length),a.companyId==='AL1'?'safety':'airline')}</div><div className="company-safety-pair"><a href={go('safety')}>Безопасность<span>События · риски · защитные меры</span></a><a href={go('safety',a.companyId==='AL1'?'service':'findings')}>Качество<span>Обязательства · замечания · эффект мер</span></a></div><p>Без общего усреднённого балла. Отклонение раскрывается до события, меры и основания.</p></>,
  };
  return <div className="al1-ceo company-overview"><CompanyNavigation route={{...route,snapshot:a.snapshotId}}/><div className="company-profile"><span>{profile}</span><span>{a.fleets.map(f=>f.aircraft).join(' · ')}</span><span>{scope.start} — {scope.end}</span></div><section className="al1-brief"><div><span>Результат · прогноз периода</span><a href={go('economics','op')}>{n(value('op'))}<small>млн ₽ · M4</small></a><p>План {n(value('op','plan'))} · факт {n(value('op','actual'))}</p></div><div><span>Готовность программы</span><a href={go('technical')}>{r.ready}/{r.planes.length}<small>ВС исправны</small></a><p><a href={go('people','crew')}>{r.confirmed}/{r.crew.length} проверок назначений пройдено</a></p></div><div><span>Требует внимания ГД</span>{urgent?<><a href={go('technical',undefined,urgent.id)}>{urgent.title}<ArrowUpRight size={18}/></a><p>Возврат {date(urgent.eta)} · план {date(urgent.planReturn)}</p></>:<a href={go('people','crew')}>Проверка обеспеченности программы</a>}</div></section><div className="al1-grid">{(Object.keys(al1Sections) as Al1Section[]).map(s=>card(s,parts[s]))}</div><section className="op-panel al1-decisions"><h2>Где требуется решение</h2><div className="al1-decision-grid">{urgent&&<a href={go('technical',undefined,urgent.id)}><b>Согласовать возврат и резерв</b><span>Технический директор · {date(urgent.eta)}</span><small>Ремонт → борт → затронутые рейсы</small></a>}{blockedCrew&&<a href={go('people','crew',blockedCrew.id)}><b>Закрыть препятствия в назначениях</b><span>Планирование экипажей</span><small>Рейс → состав → проверка допуска</small></a>}<a href={go('finance',a.companyId==='AL1'?'calendar':'liquidity')}><b>{minimum<e.cashFloor?'Обеспечить запас ликвидности':'Проверить платёжный календарь'}</b><span>Казначейство · горизонт 13 недель</span><small>Минимум {n(minimum)} млн ₽ · резерв {n(e.cashFloor)}</small></a></div></section></div>;
}
