'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,Building2,ChevronRight,FileText,Plane,UserRound} from 'lucide-react';
import {CartesianGrid,Line,LineChart,ReferenceLine,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import ThemeControl from './theme-control';
import {ownerHref,type OwnerRoute} from '@/lib/owner-model';
import {entity,factorNames,factorOwners,monthNames,recovery,rotation,type OpSnapshot,type OpCompany} from '@/lib/operating-model';

const n=(v:number|null|undefined)=>typeof v==='number'?new Intl.NumberFormat('ru-RU',{maximumFractionDigits:2}).format(v).replace('-','−'):'—';
const sign=(v:number)=>v>0?'+'+n(v):n(v);
const aliases:Record<string,string>={TECH1:'MRO-1',TECH2:'MRO-2',ENGINEER:'ENG',LESSOR:'LEASE'};
const descriptions:Record<string,string>={AL1:'Ил-76 · Ан-124',AL2:'Boeing 737-400',AL3:'Boeing 747-400','MRO-1':'ТО иностранной техники','MRO-2':'ТО российской техники',ENG:'Инжиниринг',LEASE:'Лизинг',INSURE:'Страхование',UK:'Управление группой'};

export default function OperatingWorkspace({route}:{route:OwnerRoute}) {
  const [data,setData]=useState<OpSnapshot|null>(null),[error,setError]=useState(''),[retry,setRetry]=useState(0);
  const [cumulative,setCumulative]=useState(false),[withAction,setWithAction]=useState(false);
  const heading=useRef<HTMLHeadingElement>(null);
  useEffect(()=>{const controller=new AbortController();setError('');setData(null);
    fetch(import.meta.env.BASE_URL + 'data/operating.json',{cache:'no-store',signal:controller.signal}).then(async r=>{const body=await r.json() as OpSnapshot & {message?:string};if(!r.ok)throw new Error(body.message);setData(body);}).catch(e=>{if(e.name!=='AbortError')setError(e.message||'Источник недоступен');});
    return ()=>controller.abort();},[retry]);
  useEffect(()=>{heading.current?.focus({preventScroll:true});setWithAction(false);},[route]);
  const id=aliases[route.company||'']||route.company||'GROUP';
  const row=data?entity(data,id):undefined;
  const group=id==='GROUP';
  const stale=!!route.snapshot&&!!data&&route.snapshot!==data.snapshot_id;
  const link=(next:Partial<OwnerRoute>={})=>ownerHref({page:'operating',company:id,field:route.field,from:route.from,snapshot:data?.snapshot_id,...next});
  const executiveReturn=id==='GROUP'&&route.from==='MANAGEMENT'?'MANAGEMENT':id==='CONSOLIDATION'?'MANAGEMENT':id;
  const detail=(name:string,extra:Partial<OwnerRoute>={})=>link({page:'op-detail',id:name,...extra});
  const isDetail=route.page==='op-detail';
  const title=route.page==='companies'?'Компании группы':row?.name||'Операционная прибыль · M4';
  const valueFor=(r:OpCompany,field=route.field)=>field==='plan'?r.plan:field==='actual'?r.actual:field==='variance'?r.forecast-r.plan:field==='ytdPlan'?r.ytd_plan:r.forecast;
  const fieldTitle=route.field==='plan'?'План года':route.field==='actual'?'Факт января–августа':route.field==='ytdPlan'?'План января–августа':route.field==='variance'?'Отклонение прогноза от плана':'Прогноз года';
  function companyList() {return <div className="op-companies">{data?.companies.map(c=><a href={link({company:c.id})} className="op-company" key={c.id}><span className="op-company-icon">{['AL1','AL2','AL3'].includes(c.id)?<Plane/>:<Building2/>}</span><span><strong>{c.name}</strong><small>{descriptions[c.id]}</small></span><span className="op-company-number"><b>{n(c.forecast)}</b><small className={c.forecast<c.plan?'op-negative':''}>{sign(c.forecast-c.plan)} к плану</small></span><ChevronRight/></a>)}</div>;}
  function source() {return data&&<details className="op-source"><summary><FileText size={17}/>Методика, источник и ответственность</summary><dl className="op-meta"><div><dt>Показатель</dt><dd>Операционная прибыль · M4 / Operating profit</dd></div><div><dt>Версия метода / срез</dt><dd>{data.method_version} / {data.snapshot_id}</dd></div><div><dt>За результат</dt><dd>{group?'ГД группы':id==='CONSOLIDATION'?'Руководитель консолидации':`ГД ${row?.name}`}</dd></div><div><dt>За данные и сверку</dt><dd>{group?'Финансовый блок группы':'Финансовый блок компании и консолидация'}</dd></div></dl><p>Роли проектные; ФИО и полномочия ещё не назначены. План года сравнивается с прогнозом года, факт января–августа — с планом того же периода.</p><p>M4 и Operating profit — один показатель: выручка минус все операционные расходы, включая амортизацию. Амортизация учитывается до M4 один раз. Финансовые статьи и налог — ниже. Полный учебный P&amp;L АК1 доступен в разделе «Экономика»; корпоративная методика требует сверки.</p><p>Источник: {data.source_fixture}. Месячные суммы распределены по явно заданным весам модели; это не наблюдаемая сезонность бизнеса. Для Авиакомпания 2 отдельно отражён августовский кейс отмен.</p><ul>{data.explicit_limits.map(t=><li key={t}>{t}</li>)}</ul><a href={import.meta.env.BASE_URL + 'data/operating.json'} target="_blank" rel="noreferrer">Открыть исходный набор JSON <ArrowRight size={16}/></a></details>;}
  function totalsTable(rows:OpCompany[]) {return <div className="op-scroll"><table className="op-table"><thead><tr><th>Компания / корректировка</th><th>План года</th><th>Факт янв–авг</th><th>План янв–авг</th><th>Прогноз сен–дек</th><th>Прогноз года</th><th>Δ года</th></tr></thead><tbody>{rows.map(c=><tr key={c.id}><th><a href={detail('totals',{company:c.id})}>{c.name}</a></th>{[c.plan,c.actual,c.ytd_plan,c.remaining,c.forecast,c.forecast-c.plan].map((v,i)=><td key={i}>{n(v)}</td>)}</tr>)}</tbody></table></div>;}
  function action() {
    if(!data||!row)return null;
    if(!group&&id!=='AL2')return <section className="op-panel"><h2>Действия по результату</h2><p>Для этой компании действия и ожидаемый эффект ещё не подготовлены. Отсутствие записи не означает, что действий нет.</p></section>;
    let proposal:ReturnType<typeof recovery>|undefined;try{proposal=recovery(data,data.snapshot_id);}catch{/* Expose unavailable rather than applying an unverified effect. */}
    return <section className="op-panel op-action"><div><span className="op-kicker">ВАРИАНТ ДЕЙСТВИЯ · НЕ УТВЕРЖДЁН</span><h2>Восстановить {data.action.rotations} ротации «Авиакомпания 2»</h2><p>Октябрь · ожидаемый эффект <b>+{n(data.action.expected_increment)} млн ₽</b>. Производственный руководитель готовит вариант; ГД «Авиакомпания 2» принимает решение в пределах полномочий.</p><p className="op-muted">Нужны подтверждение ресурса, полная оценка дополнительных затрат и финансовая проверка. Срок решения и ФИО не назначены. Выполнение и фактический эффект не подтверждены.</p></div><div className="op-action-control"><button className="ops-primary" disabled={!proposal} aria-pressed={withAction} onClick={()=>setWithAction(v=>!v)}>{withAction?'Сбросить вариант':'Посмотреть вариант +8'}</button><span>Базовый прогноз <b>{n(row.forecast)}</b></span>{withAction&&proposal&&<output>С действием <strong>{n(group?proposal.group:proposal.company)}</strong> млн ₽<small>Вариант расчёта, не новый прогноз</small></output>}<a href={detail('action')}>Условия и статус эффекта <ArrowRight size={16}/></a></div></section>;
  }
  function summary() {
    if(!data||!row)return null;
    let cp=0,ca=0,cf=0;
    const chart=data.monthly[id].map((p,i)=>{cp+=p.plan;ca+=p.actual??0;cf+=p.actual??p.forecast??0;return {...p,plan:cumulative?Math.round(cp*100)/100:p.plan,actual:p.actual===null?null:cumulative?Math.round(ca*100)/100:p.actual,forecast:cumulative?(i===7?Math.round(ca*100)/100:i>7?Math.round(cf*100)/100:null):p.forecast};});
    const factorRows=Object.entries(row.drivers).sort((a,b)=>Math.abs(b[1])-Math.abs(a[1]));
    const max=Math.max(1,...factorRows.map(([,v])=>Math.abs(v)));
    return <>
      <div className="op-title-row"><div><span className="op-kicker">OPERATING PROFIT</span><h2>Операционная прибыль · M4</h2><p>{group?'Результат компаний и отдельные корректировки консолидации':'Собственный результат компании до корректировок группы'} · млн ₽</p></div><a href={detail('totals')} className="op-text-link">Открыть состав <ArrowRight/></a></div>
      <div className="op-kpis">
        <a href={detail('totals',{field:'plan'})}><span>План · 2026</span><strong>{n(row.plan)}</strong><small>Годовое задание <ArrowRight size={16}/></small></a>
        <a href={detail('totals',{field:'actual'})}><span>Факт · январь–август</span><strong>{n(row.actual)}</strong><small>План периода {n(row.ytd_plan)} · <b className={row.actual<row.ytd_plan?'op-negative':''}>{sign(row.actual-row.ytd_plan)}</b></small></a>
        <a className="op-main-kpi" href={detail('totals',{field:'forecast'})}><span>Прогноз · 2026</span><strong>{n(row.forecast)}</strong><small><b className={row.forecast<row.plan?'op-negative':''}>{sign(row.forecast-row.plan)}</b> к плану года <ArrowRight size={16}/></small></a>
      </div>
      <div className="op-board"><section className="op-panel op-trend"><div className="op-section-head"><h2>Как идём к результату</h2><div className="op-switch" aria-label="Вид динамики"><button aria-pressed={!cumulative} onClick={()=>setCumulative(false)}>По месяцам</button><button aria-pressed={cumulative} onClick={()=>setCumulative(true)}>С начала года</button></div></div><div className="op-legend"><span><i className="op-plan"/>План</span><span><i className="op-actual"/>Факт</span><span><i className="op-forecast"/>{cumulative?'Факт + будущий прогноз':'Будущий прогноз'}</span></div>
        <div className="op-chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={chart} margin={{top:16,right:18,left:-10,bottom:8}} accessibilityLayer><CartesianGrid vertical={false} stroke="var(--line)" strokeDasharray="3 5"/><XAxis dataKey="label" tick={{fill:'var(--muted)',fontSize:12}} axisLine={false} tickLine={false} interval="preserveStartEnd" minTickGap={14}/><YAxis tick={{fill:'var(--muted)',fontSize:12}} axisLine={false} tickLine={false}/><Tooltip contentStyle={{background:'var(--paper)',color:'var(--ink)',border:'1px solid var(--line)',borderRadius:10}} formatter={(v,name)=>[n(Number(v))+' млн ₽',name]} labelFormatter={(_,payload)=>payload?.[0]?.payload?.month||''}/><ReferenceLine y={0} stroke="var(--muted)"/><Line name="План" dataKey="plan" stroke="var(--muted)" strokeWidth={2} strokeDasharray="4 5" dot={false} isAnimationActive={false}/><Line name="Факт" dataKey="actual" stroke="var(--op-fact)" strokeWidth={3} dot={{r:4}} isAnimationActive={false}/><Line name={cumulative?'Факт + прогноз':'Прогноз'} dataKey="forecast" stroke="var(--blue)" strokeWidth={3} strokeDasharray="7 4" dot={{r:4}} isAnimationActive={false}/></LineChart></ResponsiveContainer></div>
        <div className="op-month-links" aria-label="Раскрыть месяц">{data.monthly[id].map(p=><a key={p.month} href={detail('month',{month:p.month})} aria-label={`Раскрыть ${p.month}`}>{p.label}<ChevronRight size={12}/></a>)}</div><p className="op-muted">Учебное распределение по месяцам. С сентября факта ещё нет.</p>
      </section><section className="op-panel op-factors"><div className="op-section-head"><h2>Почему ниже плана</h2><a href={detail('factors')} aria-label="Все факторы"><ArrowRight/></a></div><p>Влияние на прогноз года · млн ₽</p><div className="op-factor-list">{factorRows.length?factorRows.map(([key,v])=><a href={detail(key)} key={key}><span>{factorNames[key]}<b className={v<0?'op-negative':''}>{sign(v)}</b></span><span className="op-factor-track"><i style={{width:`${Math.abs(v)/max*100}%`}}/></span></a>):<p>Отклонение отсутствует. Состав результата доступен отдельно.</p>}</div><a className="op-period-gap" href={detail('totals',{field:'variance'})}><span>Уже в факте <b>{sign(row.actual-row.ytd_plan)}</b></span><span>В будущих месяцах <b>{sign(row.remaining-(row.plan-row.ytd_plan))}</b></span><ChevronRight/></a></section></div>
      {group?<section className="op-panel"><div className="op-section-head"><h2>Кто формирует результат</h2><span>Прогноз года · млн ₽</span></div>{companyList()}<a className="op-consolidation" href={link({company:'CONSOLIDATION'})}><span>Корректировки консолидации<small>Отдельно от результатов компаний</small></span><b>{n(data.consolidation.forecast)}</b><ChevronRight/></a></section>:<section className="op-panel"><h2>Ответственность и глубина данных</h2><p><UserRound size={18}/> За результат — {id==='CONSOLIDATION'?'руководитель консолидации':`ГД ${row.name}`}. За расчёт и сверку — финансовый блок.</p><p className="op-muted">{id==='AL2'?'Детализирован кейс отменённых ротаций. Разбивка полного результата по программам и статьям пока отсутствует.':'Доступны годовой и месячный расчёты, а также факторы. Полный состав по программам, статьям и документам ещё не подготовлен.'}</p>{id==='AL2'&&<a href={detail('aog')} className="op-text-link">Отменённые ротации: {n(data.aog_case.expected_effect)} млн ₽ <ArrowRight/></a>}{['AL1','AL2','AL3'].includes(id)&&<p><a href={ownerHref({page:'production',company:id})}>Полётная программа компании <ArrowRight size={16}/></a><small className="op-muted"> Отдельный учебный набор; с этой прибылью пока не связан.</small></p>}</section>}
      {id!=='CONSOLIDATION'&&action()}
    </>;
  }
  function detailView() {
    if(!data||!row)return null;
    const key=route.id||'';
    if(key==='totals')return <section className="op-panel"><h2>{fieldTitle}</h2><div className="op-detail-number">{n(valueFor(row))}<small>млн ₽</small></div><p>Прогноз года = факт января–августа + прогноз сентября–декабря: {n(row.actual)} + {n(row.remaining)} = {n(row.forecast)}.</p>{totalsTable(group?[...data.companies,entity(data,'CONSOLIDATION')!,row]:[row])}<p className="op-muted">Полный P&amp;L до финансовых статей ещё не подготовлен. Ниже доступна помесячная модель; суммы нельзя трактовать как первичные проводки.</p><div className="op-month-links">{data.monthly[id].map(p=><a key={p.month} href={detail('month',{month:p.month})}>{p.label}<ChevronRight size={12}/></a>)}</div></section>;
    if(key==='month') {
      const point=data.monthly[id].find(p=>p.month===route.month);
      if(!point)return <section className="op-panel"><h2>Месяц недоступен</h2><p>Период не найден в этом снимке. Значение не подставлено.</p></section>;
      const rows=group?[...data.companies,entity(data,'CONSOLIDATION')!]:[row];
      const selected=route.field==='plan'?point.plan:route.field==='ytdPlan'?(point.actual===null?null:point.plan):route.field==='actual'?point.actual:route.field==='variance'?(point.actual??point.forecast??0)-point.plan:point.actual??point.forecast;
      const selectedLabel=route.field==='plan'||route.field==='ytdPlan'?'план':route.field==='actual'?'факт':route.field==='variance'?'отклонение':point.actual===null?'прогноз':'факт';
      return <section className="op-panel"><h2>{monthNames[Number(point.month.slice(-2))-1]} 2026 · {row.name}</h2><div className="op-detail-number">{n(selected)}<small>млн ₽ · {selectedLabel}</small></div><p>{selected===null?'Выбранный факт / закрытый план в этом месяце отсутствует. ':''}План месяца {n(point.plan)} · отклонение {sign((point.actual??point.forecast??0)-point.plan)} млн ₽.</p><div className="op-scroll"><table className="op-table"><thead><tr><th>Компания / корректировка</th><th>План месяца</th><th>{point.actual===null?'Прогноз':'Факт'} месяца</th><th>Δ месяца</th></tr></thead><tbody>{rows.map(c=>{const m=data.monthly[c.id].find(p=>p.month===point.month)!;return <tr key={c.id}><th><a href={detail('month',{company:c.id,month:point.month})}>{c.name}</a></th><td>{n(m.plan)}</td><td>{n(m.actual??m.forecast)}</td><td>{sign((m.actual??m.forecast??0)-m.plan)}</td></tr>;})}</tbody></table></div><p className="op-muted">Основание суммы — синтетическое распределение годового сценария. Корпоративных документов за месяц здесь нет.</p>{id==='AL2'&&point.month==='2026-08'&&<a href={detail('aog')}>Кейс августа: отменённые ротации, влияние {n(data.aog_case.expected_effect)} <ArrowRight size={16}/></a>}</section>;
    }
    if(key==='action')return group||id==='AL2'?<>{action()}<section className="op-panel"><h2>Контроль включения эффекта</h2><p>{data.action.rotations} ротации × {n(data.action.net_increment_per_rotation)} млн ₽ чистого дополнительного эффекта = +{n(data.action.expected_increment)} млн ₽. Условная маржа уже включает все дополнительные операционные расходы.</p><p>Вариант не утверждён. В базовый прогноз не включён. Фактический эффект: не получен.</p><p>После проверки финансовым блоком и публикации новой версии эффект отмечается «включён» и повторно не прибавляется. +8 прибыли не означает +8 денег в октябре.</p><p>Основание: {data.action.id}. Исходный срез: {data.snapshot_id}.</p></section></>:<section className="op-panel"><h2>Действие недоступно</h2><p>Этот кейс относится к «Авиакомпания 2», не к выбранной компании.</p></section>;
    if(key.startsWith('AL2-ROT-')) {
      const r=id==='AL2'?rotation(data,key):undefined;
      return <section className="op-panel"><h2>{r?'Учебная запись отмены':'Запись недоступна'}</h2>{r?<><p>{r.id} · август 2026 · B737-400</p><div className="op-scroll"><table className="op-table"><thead><tr><th>Строка расчёта</th><th>План</th><th>Факт</th><th>Влияние на прибыль</th></tr></thead><tbody><tr><th>Выручка</th><td>{n(r.planRevenue)}</td><td>{n(r.actualRevenue)}</td><td>{sign(r.actualRevenue-r.planRevenue)}</td></tr><tr><th>Избегаемые переменные расходы</th><td>{n(r.planCost)}</td><td>{n(r.actualCost)}</td><td>{sign(r.planCost-r.actualCost)}</td></tr><tr><th>Итого</th><td>{n(r.planRevenue-r.planCost)}</td><td>{n(r.actualRevenue-r.actualCost)}</td><td>{n(r.impact)}</td></tr></tbody></table></div><p>Основания сценария: плановые строки дохода и затрат, учебная запись отмены, допущение об отмене обязательств перед поставщиками без удержаний. Уже предусмотренные постоянные расходы не исчезают.</p><p className="op-muted">Это синтетическая запись, не реальный рейс и не документ из корпоративной системы. «Акт потерянной прибыли» не создаётся. Ответственные за подтверждение — производство, закупки и финансы; ФИО не назначены.</p><a href={detail('aog')}>Все {data.aog_case.rotation_count} ротаций <ArrowRight size={16}/></a></>:<p>Проверьте компанию и идентификатор. Чужая запись не подставляется.</p>}</section>;
    }
    if(key==='aog'&&id==='AL2')return <section className="op-panel"><h2>Простой и отмены · август</h2><div className="op-detail-number">{n(data.aog_case.expected_effect)}<small>млн ₽ к годовому плану</small></div><p>{data.aog_case.rotation_count} ротаций × (−{n(data.aog_case.revenue_per_rotation)} потерянной выручки + {n(data.aog_case.avoidable_cost_per_rotation)} избежанных расходов) = {n(data.aog_case.expected_effect)}. Это часть отклонения компании {n(row.forecast-row.plan)}, а не дополнительный убыток поверх него.</p><p>За восстановление — технический руководитель; производство подтверждает отмены, закупки — снятые обязательства, финансы — влияние на прибыль.</p><div className="op-rotation-grid">{Array.from({length:data.aog_case.rotation_count},(_,i)=>`AL2-ROT-${String(i+1).padStart(3,'0')}`).map(r=><a key={r} href={detail(r)}><FileText size={17}/>{r}<b>{n(rotation(data,r)?.impact)}</b><ChevronRight size={17}/></a>)}</div><p className="op-muted">Все записи учебные. Эти ротации не добавлены в существующий реестр налёта.</p><a href={detail('action')}>Вариант восстановления будущей программы <ArrowRight size={16}/></a></section>;
    if(key==='consolidation'&&id!=='GROUP'&&id!=='CONSOLIDATION')return <section className="op-panel"><h2>Корректировка вне периметра</h2><p>Групповая корректировка не относится к собственному результату выбранной компании.</p></section>;
    if(key==='consolidation')return <section className="op-panel"><h2>Корректировка консолидации</h2><div className="op-detail-number">{n(data.consolidation.forecast)}<small>млн ₽ · декабрь, прогноз</small></div><p>Учебное исключение прибыли от внутригрупповой передачи актива, ещё не реализованной вне группы. Корректировка хранится отдельно; она не распределена на компании без основания.</p><p>Обычное парное исключение выручки и расходов по внутреннему ТО не уменьшает прибыль группы на сумму оборота. Налоговые эффекты этого примера не рассчитаны.</p><p className="op-muted">Источник — модельное допущение. Журнал реальных корректировок и исходные документы не подключены.</p></section>;
    const selected=key==='factors'?Object.keys(row.drivers):key in row.drivers?[key]:[];
    return <section className="op-panel"><h2>{key==='factors'?'Факторы отклонения':factorNames[key]||'Основание недоступно'}</h2>{selected.length?selected.map(f=><div className="op-factor-detail" key={f}><h3>{factorNames[f]} <span className="op-negative">{sign(row.drivers[f])} млн ₽</span></h3><p>Ответственная роль: {factorOwners[f]}. Финансовый блок сверяет расчёт.</p>{group?<div className="op-factor-companies">{data.companies.filter(c=>c.drivers[f]!==undefined).map(c=><a href={detail(f,{company:c.id})} key={c.id}><span>{c.name}</span><b>{sign(c.drivers[f])}</b><ChevronRight size={16}/></a>)}{f==='consolidation'&&<a href={detail('consolidation',{company:'CONSOLIDATION'})}>Групповая корректировка {n(data.consolidation.forecast)} <ChevronRight size={16}/></a>}</div>:<><p className="op-muted">Заданный фактор учебного сценария. Исходные объёмы, ставки и финансовые строки для его независимого пересчёта ещё не подготовлены. Сходимость суммы не доказывает причину в реальном бизнесе.</p>{f==='aog'&&id==='AL2'&&<a href={detail('aog')}>Открыть расчёт 12 отмен <ArrowRight size={16}/></a>}</>}</div>):<p>Для выбранной компании такой фактор отсутствует. Ноль и вымышленное основание не подставлены.</p>}</section>;
  }
  return <div className="aviation-app overview-glass op-app"><a className="skip-link" href="#op-workspace" onClick={e=>{e.preventDefault();document.getElementById("op-workspace")?.focus();}}>К содержанию</a><header className="app-header"><a href="#/overview" className="brand"><span>AG</span></a><span className="role-label"><UserRound/>{group?'Владелец–ГД группы':id==='CONSOLIDATION'?'Консолидация':'ГД компании'}</span><nav aria-label="Основная навигация"><a href="#/overview" className={group&&route.page!=='companies'?'active':''}>Обзор</a><a href="#/companies" className={route.page==='companies'||!group?'active':''}>Компании</a><a href="#/production">Налёт</a><a href="#/legacy">Архив демо</a></nav><div className="header-tools"><ThemeControl/><span className="source-badge demo">Учебные данные</span></div></header>
    <main className="workspace" id="op-workspace" tabIndex={-1}><div className="page-heading"><div><h1 tabIndex={-1} ref={heading}>{title}</h1><p>2026 · факт по 31 августа · прогноз сентября–декабря · млн ₽</p></div><a href={ownerHref({page:executiveReturn==='GROUP'?'overview':'company',company:executiveReturn})} className="back-link"><ArrowLeft/>К управленческому экрану {executiveReturn==='MANAGEMENT'?'УК':executiveReturn==='GROUP'?'Авиагруппа':row?.name}</a></div>
      {error?<section className="op-panel" role="alert"><h2>Источник недоступен</h2><p>{error}</p><button className="ops-primary" onClick={()=>setRetry(v=>v+1)}>Повторить</button></section>:!data?<output>Загружаем операционную прибыль…</output>:stale?<section className="op-panel" role="alert"><h2>Версия данных изменилась</h2><p>Ссылка относится к другому снимку. Старые и новые суммы не объединяются.</p><a href={link({page:'operating',id:undefined,month:undefined})}>Открыть актуальный срез</a></section>:!row?<section className="op-panel"><h2>Компания не найдена</h2><a href="#/companies">Открыть компании</a></section>:<>
        {isDetail&&<nav className="op-trail" aria-label="Путь раскрытия"><a href={detail('totals',{company:'GROUP',month:undefined})}>AG · {fieldTitle.toLowerCase()} {n(valueFor(entity(data,'GROUP')!))}</a>{!group&&<><ChevronRight size={16}/><a href={detail('totals',{month:undefined})}>{row.name} · {fieldTitle.toLowerCase()} {n(valueFor(row))}</a></>}<ChevronRight size={16}/><span>{route.id==='month'?route.month:route.id==='totals'?fieldTitle:factorNames[route.id||'']||'Основание / действие'}</span><a href={link({id:undefined,month:undefined})}>Экран {group?'группы':'компании'}</a></nav>}
        {route.page==='companies'?<><p className="op-muted">Прямой вход в экран ГД компании. Прогноз года, млн ₽.</p>{companyList()}</>:isDetail?detailView():summary()}
        {source()}<footer className="op-footer"><span>{data.snapshot_id} · {data.method_version}</span><span>Две роли — один финансовый снимок. Переключение роли не выдаёт права доступа.</span></footer>
      </>}
    </main></div>;
}
